/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.saxonica.xmldoclet;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        XmlDoclet classUnderTest = new XmlDoclet();
        assertTrue(true);
    }
}
