/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.saxonica.xmldoclet;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class ParseTest {
/*
    @Test void noPackageName() {
        TreeConstructor builder = new TreeConstructor();
        XmlProcessorX proc = new XmlProcessorX(builder, null);
        Assertions.assertEquals("", proc.packageName("Test"));
        Assertions.assertEquals("", proc.packageName("Test<org.example.Spoon>"));
    }

    @Test void packageName() {
        TreeConstructor builder = new TreeConstructor();
        XmlProcessorX proc = new XmlProcessorX(builder, null);
        Assertions.assertEquals("org.example", proc.packageName("org.example.Test"));
        Assertions.assertEquals("org.example", proc.packageName("org.example.Test<org.example.Spoon>"));
    }

    @Test void noPackageClassName() {
        TreeConstructor builder = new TreeConstructor();
        XmlProcessorX proc = new XmlProcessorX(builder, null);
        Assertions.assertEquals("Test", proc.className("Test"));
        Assertions.assertEquals("Test<org.example.Spoon>", proc.className("Test<org.example.Spoon>"));
    }

    @Test void className() {
        TreeConstructor builder = new TreeConstructor();
        XmlProcessorX proc = new XmlProcessorX(builder, null);
        Assertions.assertEquals("Test", proc.className("org.example.Test"));
        Assertions.assertEquals("Test<org.example.Spoon>", proc.className("org.example.Test<org.example.Spoon>"));
    }

    @Test void typeName() {
        TreeConstructor builder = new TreeConstructor();
        XmlProcessorX proc = new XmlProcessorX(builder, null);
        Assertions.assertEquals("HashMap<Symbol,HashMap<Long,ForestNode>>",
                proc.className("java.lang.HashMap<a.b.c.Symbol,java.lang.HashMap<java.lang.Long,d.e.f.ForestNode>>"));
    }

 */
}
